### ISSUE TITLE
Not working with Tomcat 10.1.18 and Java17

### ISSUE THREAD

**Issue by tglion** [Waffle/waffle#2273]
If I try to browse a web-page which is configured with waffle 3.3.0 I get an error-message:
java.lang.NoSuchMethodError: 'void waffle.util.AuthorizationHeader.<init>(jakarta.servlet.http.HttpServletRequest)'
	waffle.apache.NegotiateAuthenticator.authenticate(NegotiateAuthenticator.java:78)
	waffle.apache.NegotiateAuthenticator.doAuthenticate(NegotiateAuthenticator.java:196)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:563)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.base/java.lang.Thread.run(Thread.java:840)

There seems to be a conflict regarding the parameter of the constructor in waffle.util.AuthorizationHeader. It uses javax.servlet.http.HttpServletRequest, but the caller probably uses jakarta.servlet.http.HttpServletRequest. Could you please take a look at it? Thank you.

**Comment by hazendaz** [comment]
There are separate modules for jakarta such as waffle-jna-jakarta.  You need to use that one instead of the former naming.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: tglion ***@***.***>
Sent: Thursday, March 14, 2024 4:15:00 AM
To: Waffle/waffle ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Waffle/waffle] Not working with Tomcat 10.1.18 and Java17 (Issue #2273)


If I try to browse a web-page which is configured with waffle 3.3.0 I get an error-message:
java.lang.NoSuchMethodError: 'void waffle.util.AuthorizationHeader.(jakarta.servlet.http.HttpServletRequest)'
waffle.apache.NegotiateAuthenticator.authenticate(NegotiateAuthenticator.java:78)
waffle.apache.NegotiateAuthenticator.doAuthenticate(NegotiateAuthenticator.java:196)
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:563)
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
java.base/java.lang.Thread.run(Thread.java:840)

There seems to be a conflict regarding the parameter of the constructor in waffle.util.AuthorizationHeader. It uses javax.servlet.http.HttpServletRequest, but the caller probably uses jakarta.servlet.http.HttpServletRequest. Could you please take a look at it? Thank you.

**Comment by tglion** [comment]
Thank you, with waffle-jna-jakarta it works now. :-)
